## Covariates

**Table 1**. List of candidate covariates for habitat and connectivity analyses.

|Covariate|Source|Filename|
| :--- | :---: | :---: |
|Topography|||
|Elevation|NRCan CDEM (GEE)|elevation.tif|
|Slope|Derived from elevation|slope.tif|
|Aspect|Derived from elevation|aspect.tif|
|Roughness|Derived from elevation|roughness.tif|
|Eastness|Derived from elevation|eastness.tif|
|Northness|Derived from elevation|northness.tif|
|Landcover & productivity|||
|Landcover (19 classes, 10 reclasses)|NALC 2020 (GEE)|nalc19.tif, nalc10.tif|
|NDVI 2020-25|MODIS NDVI (GEE)|ndvi_2020-25.tif|
|Disturbances|||
|Burned areas 1984-2024|National Burned Area Composite|burns.tif|
|Areal disturbances|YG, Beacons, etc.|disturbances.gpkg (areal)|
|Linear disturbances|YG, Beacons, etc.|disturbances.gpkg (linear)|
|Climate variables|||
|Bioclimate (1960-90)|Worldclim website|bioclim.tif (19 bands)|
|Bioclimate future scenario 1|Worldclim website|bioclim_future_scenario1|
|Bioclimate future scenario 2|Worldclim website|bioclim_future_scenario2|

## References

**General**

Dobrowski et al. 2021. Protected-area targets could be undermined by climate change-driven shifts in ecoregions and biomes. Communications Earth & Environment 2(1):1-11.

Rudolph 2019.

Tompalski 2024 (example of using FRI data)

**Movement**

Anderson, M.G., Barnett, A., Clark, M., Prince, J., Olivero Sheldon, A. and Vickery B. 2016. Resilient and Connected Landscapes for Terrestrial Conservation. The Nature Conservancy, Eastern Conservation Science, Eastern Regional Office. Boston, MA.

Joo et al. 2019. Navigating through the r packages for movement.

Joo et al. 2022. Recent trends in movement ecology of animals and human mobility.

Keeley et al. 2021. Connectivity metrics for conservation planning and monitoring. Biological Conservation 255:109088.

Nathan 2008. A movement ecology paradigm for unifying organismal movement research.

Nathan et al. 2022. Big-data approaches lead to an increased understanding of the ecology of animal movement.

Parks et al. 2020. Human land uses reduce climate connectivity across North America. Global Change Biology 26(5):2944-2955.

Saura, S., Bastin, L., Battistella, L., Mandrici, A., & Dubois, G. 2017. Protected areas in the world's ecoregions: How well connected are they? Ecological Indicators 76:144-158.

Ward et al. 2020. Just ten percent of the global terrestrial protected area network is structurally connected via intact land. Nature Communications.

**Resistance**

Dutta et al. 2022. An overview of computational tools for preparing, constructing and using resistance surfaces in connectivity research.

Kumar et al. 2022. Moving beyond landscape resistance: considerations for the future of connectivity modelling and conservation science.

**Connectivity**

Iverson et al. 2024. Functional landscape connectivity for a select few: Linkages do not consistently predict wildlife movement or occupancy.

Keeley et al. 2024. Comment on Functional landscape connectivity for a select few: Linkages do not consistently predict wildlife movement or occupancy. Autum R. Iverson, David Waetjen, Fraser Shilling.

Pither et al. 2023. Predicting areas important for ecological  connectivity throughout Canada.

Poor et al. 2024. Towards robust corridors: a validation framework to improve corridor modeling.

**Habitat modelling**

O'Malley 2024. Machine learning allows for large‑scale habitat prediction.

**Scale of effect**

Branney et al. 2024. Scale of effect of landscape patterns on resource selection by bobcats (Lynx rufus) in a multi‐use rangeland system.

Carpentier et al. 2021. Siland a R package for estimating  the spatial influence of landscape.

Lowe et al. 2022. ‘Scalescape’: an R package for estimating distance‐weighted landscape effects on an environmental response.

Moraga et al. 2019. The scale of effect of landscape context varies with the species’ response variable measured.

**Background points**

Whitford et al. 2024. The influence of the number and distribution of background points in presence-background species distribution models.

**Sample size, positional uncertainty, and sampling bias**

Moudry et al. 2024. Optimising occurrence data in species distribution models: sample size, positional uncertainty, and sampling bias matter.
